name: 部署 Firebase
on:
  push:
    branches:
      - master
      - test

jobs:
  build:
    name: 打包
    runs-on: ubuntu-latest
    steps:
      - name: 搭建 node 环境
        uses: actions/checkout@master
        with:
          node-version: '14'

      - name: 安装依赖
        run: npm install

      - name: 正式服构建
        if: github.ref == 'refs/heads/master'
        run: npm run build

      - name: 测试服构建
        if: github.ref == 'refs/heads/test'
        run: npm run build:test

      - name: 上传打包文件
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy:
    name: 部署
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库
        uses: actions/checkout@master
      - name: 下载打包文件
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Firebase 部署正式服
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Firebase 部署测试服
        if: github.ref == 'refs/heads/test'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
